spring:
  application:
    name: notification-service

  profiles:
    active: elk

server:
  port: 8082

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0      # ? ???? ????? 100%, ? production ?????? (0.1, 0.01)
    propagation:
      consume: w3c
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
          - loggers