input {
  beats {
    port => 5000
  }
}

filter {
  mutate {
    rename => {
      "traceId" => "[trace][id]"
      "spanId"  => "[span][id]"
      "service" => "[service][name]"
      "level"   => "[log][level]"
      "logger_name" => "[log][logger]"
      "thread_name" => "[process][thread][name]"
    }

    remove_field => [
      "@version",
      "[event][original]",
      "[container][labels]",
      "[agent][ephemeral_id]",
      "[agent][ephemeral_id]",
      "[agent][id]",
      "[ecs][version]"
    ]

    add_field => {
      "event.dataset" => "orderhub.logs"
      "event.module"  => "orderhub"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orderhub-logs-%{+YYYY.MM.dd}"
  }
}